// FROZEN — DO NOT MODIFY (hash in tests/FROZEN_MANIFEST.sha256)
// SPDX-License-Identifier: Apache-2.0
// T-001 Pitch helpers (D-001). Expected literals generated by research/spikes/expected_values.py (EXPECTED:<name>).
#include "TestSupport.h"
#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

using Catch::Approx;

TEST_CASE("T-001 equal temperament and cents", "[T-001][unit]") {
    CHECK(tpt::equalTemperedHz(69) == Approx(440.0).epsilon(1e-12));                          // EXPECTED:et_69_440
    CHECK(tpt::equalTemperedHz(58) == Approx(233.08188075904496).epsilon(1e-12));             // EXPECTED:et_58_440
    CHECK(tpt::equalTemperedHz(52) == Approx(164.81377845643496).epsilon(1e-12));             // EXPECTED:et_52_440
    CHECK(tpt::equalTemperedHz(87) == Approx(1244.5079348883237).epsilon(1e-12));             // EXPECTED:et_87_440
    CHECK(tpt::equalTemperedHz(82, 442.0) == Approx(936.5653754136171).epsilon(1e-12));       // EXPECTED:et_82_442
    CHECK(tpt::centsBetween(880.0, 440.0) == Approx(1200.0).epsilon(1e-12));                   // EXPECTED:cents_880_440
    CHECK(tpt::centsBetween(466.0, 440.0) == Approx(99.39171735554476).epsilon(1e-12));        // EXPECTED:cents_466_440
    CHECK_THROWS_AS(tpt::centsBetween(0.0, 440.0), std::invalid_argument);
    CHECK_THROWS_AS(tpt::centsBetween(440.0, -1.0), std::invalid_argument);
    CHECK(tpt::kTransposition == 2);
}

TEST_CASE("T-001 note names", "[T-001][unit]") {
    CHECK(tpt::noteName(60) == "C4");
    CHECK(tpt::noteName(54) == "F#3");
    CHECK(tpt::noteName(70) == "A#4");
    CHECK(tpt::noteName(89) == "F6");
    CHECK(tpt::noteName(0) == "C-1");
    CHECK(tpt::noteName(127) == "G9");
    CHECK_THROWS_AS(tpt::noteName(-1), std::out_of_range);
    CHECK_THROWS_AS(tpt::noteName(128), std::out_of_range);
}
